name: Update Podcasts Index

on:
  push:
    paths:
      - '**/index.html'
      - 'generate_podcasts.py'
      - '.github/workflows/update-podcasts.yml'

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run podcast generator
      run: python generate_podcasts.py

    - name: Commit and push updated podcasts.json
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
        git add podcasts.json
        git diff --cached --quiet || (git commit -m "Automatisch bijgewerkte podcasts.json" && git push)
